version : "3"
services:
  docker-node:
    build: 
      context: .
      target: production
      # args: 
      #   NODE_ENV: production
    ports:
      - 3000:3000
    # environment:
    #   - NODE_ENV=production
    # command: npm run start